sources: # you can provide either single path or several paths using `-`
  - ToolingSample
templates:
  - ToolingSample/Common/Sourcery/Templates # as well as for templates
output:
  ToolingSample/Common/Sourcery.generated.swift # note that there is no `-` here as only single output path is supported
