# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'ToolingSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToolingSample
  #pod 'SwiftLint', '0.30.1'
  #pod 'Sourcery', '0.15.0'
  #pod 'R.swift', '5.0.2'

end
