# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    xcode_select("/Applications/Xcode.app")
    cocoapods(use_bundle_exec: true)
  end

  desc "Run unit tests"
  lane :unit_tests do |values|
    scan(
      workspace: 'LocationTracker.xcworkspace',
      scheme: 'LocationTracker',
      clean: true
    )
  end

  desc "Build project and male archive"
  lane :build do |values|
    gym(
      workspace: 'LocationTracker.xcworkspace',
      scheme: 'LocationTracker',
      clean: true,
      export_method: 'development',
      configuration: 'Debug'
    )
  end

end
