sources:
  - TestStorage # you can provide either single path or several paths using `-`
templates:
  - TestStorage/Common/Sourcery/Templates # as well as for templates
output:
  TestStorage/Common/Sourcery/Sourcery.generated.swift # note that there is no `-` here as only single output path is supported
