# frozen_string_literal: true

source "https://rubygems.org"

gem 'fastlane', '2.128.1'
gem "cocoapods", '1.7.5'
gem "xcode-install", '2.6.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
